sidebar:
  case:
    name: "朋友圈推广案例"
    url: "case"
  ue:
    name: "视觉交互规范"
    url: "ue"
  template:
    name: "模版详情页规范"
    url: "template"
  dev:
    name: "自定义详情页技术规范"
    url: "dev"
  Workflow:
    name: "自定义详情页前端工作流"
    url: "workflow"
    url2: "workflow-simple"
  WxMoment:
    name: "自定义详情页前端通用库"
    url: "WxMoment"
  faq:
    name: "常见问题答疑"
    url: "faq"


less:
  paths:
    - source/css/_mp/base.less
    - source/css/_mp/doc.less